"""test_genetic_programming: package of unittest of genetic_programing package"""

from test_genetic_programming.test_node import NodeTest
from test_genetic_programming.test_null_node import NullNodeTest
from test_genetic_programming.test_terminal_node import TerminalNodeTest
from test_genetic_programming.test_binary_node import BinaryNodeTest
from test_genetic_programming.test_yes_no_node import YesNoNodeTest
from test_genetic_programming.test_ast import ASTTest
from test_genetic_programming.test_asbt import BinaryASTTest
from test_genetic_programming.test_chiffres_yes_no_variant import ChiffresVariantTest
from test_genetic_programming.test_boolean_node import BooleanNodeTest
from test_genetic_programming.test_if_then_else_node import IfThenElseTest
from test_genetic_programming.test_variable import BooleanVariableNodeTest, BinaryVariableNodeTest
from test_genetic_programming.test_equation_guesser import EquationGuesserTest
