"""individual: Package of individuals"""

from genetic_algorithm.individuals.individual import Individual
from genetic_algorithm.individuals.multi_objective_individual import MultiObjectiveIndividual
from genetic_algorithm.individuals.null_individual import NullIndividual
from genetic_algorithm.individuals.word_guesser import WordGuesser
from genetic_algorithm.individuals.sentence_guesser import SentenceGuesser
from genetic_algorithm.individuals.binary_calculator import BinaryCalculator
from genetic_algorithm.individuals.travel_path import TravelPath
from genetic_algorithm.individuals.robot_in_maze import RobotInMaze
